---
name: ambassador

dockerImage: quay.io/datawire/ambassador:0.32.2

profiles:
  stable:
    namespace: stable
  edge:
    namespace: edge
  development:
    namespace: development

branches:
  master: stable
  rc/*: edge
  dev/*: development
