---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin
  namespace: {{ build.profile.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8877
      targetPort: admin
  selector:
    app: ambassador

---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: {{ build.profile.namespace }}
spec:
  type: NodePort
  ports:
    - name: envoy
      port: 80
      targetPort: envoy
  selector:
    app: ambassador
